name: Build Python

on:
  push:
    paths:
      - 'SAST/python/**'
      - 'SAST/python/build.yml'
  pull_request:
    paths:
      - 'SAST/python/**'
      - 'SAST/python/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compile Python files
        run: |
          python -m compileall SAST/python
