name: Build Ruby

on:
  push:
    paths:
      - 'SAST/ruby/**'
      - 'SAST/ruby/build.yml'
  pull_request:
    paths:
      - 'SAST/ruby/**'
      - 'SAST/ruby/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Syntax check Ruby file
        run: ruby -c SAST/ruby/sample.rb
